---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_osx: true
configure_k9s: true

dotfiles_repo: git@github.com:mboggess-signify/signify-health-sre-dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/git/GitHub/signify-health-sre-dotfiles
dotfiles_home: ~/
dotfiles_files:
  - .aliases
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .zshrc
dotfiles_folders:
  - .kube
dotfiles_folders_docs:
  - .kube/add-configs-here.txt

homebrew_installed_packages:
  - autoconf
  - azure-cli
  - bash-completion
  - cowsay
  - derailed/k9s/k9s
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - gnu-sed
  - go
  - gpg
  - httpie
  - iperf
  - jq
  - kubectl
  - libevent
  - mcrypt
  - nmap
  - node
  - nvm
  - openssl
  - php
  - pv
  - readline
  - ssh-copy-id
  - sqlite
  - tree
  - wget
  - wrk
  - zsh-history-substring-search
  - sgfy/sgfy-homebrew/ado
  - sgfy/sgfy-homebrew/azpdocs
  - sgfy/sgfy-homebrew/pbt
  - sgfy/sgfy-homebrew/stagehand

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - { name: sgfy/sgfy-homebrew, url: 'https://dev.azure.com/signifyhealth/HCC/_git/sgfy-homebrew'}

homebrew_cask_appdir: /Applications
homebrew_cask_apps: []

# k9s
k9s_skins_files:
  - hcc-dev-usc-shared-aks-admin_skin.yml
  - hcc-prod-usc-shared-aks-admin_skin.yml
  - hcc-qa-usc-shared-aks-admin_skin.yml
  - hcc-uat-usc-shared-aks-admin_skin.yml

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
pip_packages:
 - name: mkdocs
   state: latest # present/absent/latest, default: present
 - name: mkdocs-techdocs-core
   state: latest 
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

  # Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
