---
- name: Check if custom k9s skins are added.
  find:
    paths: "/Users/mboggess/Library/Application Support/k9s/"
    patterns: "*.*"
  register: filesFound

- debug:
  #    msg: "Directory is empty. Proceeding."
    var: filesFound.examined 
  when: filesFound.examined < 2

- name: Ensure custom k9s skins are added.
  copy:
    src: "files/k9s/skins/{{ item }}"
    dest: "/Users/mboggess/Library/Application Support/k9s/{{ item }}"
  become: false
  with_items: "{{ k9s_skins_files }}"
  when: filesFound.examined < 2
