---
- name: Ensure custom k9s skins are added.
  copy:
    src: "files/k9s/skins/{{ item }}"
    dest: "/Users/mboggess/Library/Application Support/k9s/{{ item }}"
  become: false
  with_items: "{{ k9s_skins_files }}"
